"""How data is split into train, validation and test (spec 3.3, ADR 0003).

GUARDED AREA -- this is the data split.

**GuitarSet is test-only.** No tuning, no hyperparameter search, no threshold sweep,
no model selection and no architecture choice may consult a GuitarSet number. There is
no GuitarSet train or validation split: not "we choose not to use one", but no such
thing exists in this project.

This module exists to make that mechanical rather than remembered:

- :func:`guitarset_test_ids` reads a committed snapshot, never a glob over whatever
  happens to be on disk, so the split cannot drift with a partial download.
- :func:`assert_tuning_allowed` raises for :attr:`Split.TEST`. Every tuning entry point
  calls it first.
- :func:`record_test_set_access` appends to an audit log, so looking at test numbers is
  a deliberate act with a written reason.
"""

from __future__ import annotations

import datetime as dt
import subprocess
from enum import Enum
from pathlib import Path

from tabsampler.errors import TestSetMisuseError

#: GuitarSet contains 360 excerpts: 6 players x 2 styles (comp/solo) x 5 progressions
#: x 3 tempi. A snapshot with any other count means a partial or corrupted download,
#: which would silently change the corpus every metric is computed over.
EXPECTED_GUITARSET_TRACKS = 360

#: The committed snapshot of test track ids, generated by scripts/download_guitarset.py
#: and reviewed in its diff. This file defines the test set for the life of the project.
DEFAULT_SNAPSHOT = Path(__file__).parent / "guitarset_test_ids.txt"

DEFAULT_ACCESS_LOG = Path("experiments/test_set_access.log")

_ACCESS_LOG_HEADER = (
    "# Every deliberate look at the test set, per ADR 0003.\n"
    "# Appended automatically by tabsampler.data.splits.record_test_set_access.\n"
    "# Columns: iso8601_utc | commit | reason\n"
)


class Split(Enum):
    """The only three splits this project recognises."""

    TRAIN = "train"
    VALIDATION = "validation"
    TEST = "test"


def guitarset_test_ids(
    snapshot: Path | None = None,
    expected_count: int | None = EXPECTED_GUITARSET_TRACKS,
) -> tuple[str, ...]:
    """The GuitarSet test track ids, read from the committed snapshot.

    Args:
        snapshot: Path to the snapshot file. Defaults to the packaged one.
        expected_count: Reject the snapshot unless it holds exactly this many ids.
            Pass ``None`` to skip the check (used only by tests with small fixtures).

    Raises:
        FileNotFoundError: if the snapshot has not been generated yet.
        ValueError: if the snapshot is empty, unsorted, contains duplicates, or has an
            unexpected number of entries.
    """
    path = DEFAULT_SNAPSHOT if snapshot is None else snapshot
    if not path.is_file():
        raise FileNotFoundError(
            f"no GuitarSet split snapshot at {path}. Generate it with "
            f"`uv run python scripts/download_guitarset.py`, then review the diff -- "
            f"this file defines the test set for the life of the project."
        )

    ids = [
        line.strip()
        for line in path.read_text().splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]

    if not ids:
        raise ValueError(
            f"the split snapshot at {path} is empty; an empty test set would evaluate "
            f"nothing and report a vacuous score"
        )
    if len(set(ids)) != len(ids):
        duplicates = sorted({i for i in ids if ids.count(i) > 1})
        raise ValueError(f"duplicate track ids in {path}: {duplicates}")
    if ids != sorted(ids):
        raise ValueError(
            f"track ids in {path} are not sorted; a stable order keeps the split "
            f"reproducible and its diffs readable"
        )
    if expected_count is not None and len(ids) != expected_count:
        raise ValueError(
            f"{path} holds {len(ids)} track ids but expected {expected_count}; "
            f"a truncated snapshot silently changes the evaluation corpus"
        )

    return tuple(ids)


def assert_tuning_allowed(split: Split) -> None:
    """Refuse to tune, select or sweep against the test split.

    Call this at the top of every entry point that fits a parameter to data.

    Raises:
        TestSetMisuseError: if ``split`` is :attr:`Split.TEST`.
    """
    if split is Split.TEST:
        raise TestSetMisuseError(
            "refusing to tune against the test split: GuitarSet is test-only "
            "(ADR 0003). Tune on a validation split drawn from training sources. "
            "Cost-weight tuning needs only symbolic tabs, so DadaGP serves that "
            "purpose with no audio at all."
        )


def record_test_set_access(
    reason: str,
    log_path: Path | None = None,
    commit: str | None = None,
) -> None:
    """Append a line to the test-set access log.

    Args:
        reason: Why the test set is being looked at. Required; an entry without a
            reason defeats the purpose of the log.
        log_path: Where to append. Defaults to ``experiments/test_set_access.log``.
        commit: Git commit to attribute the look to. Resolved automatically if omitted.

    Raises:
        ValueError: if ``reason`` is blank.
    """
    if not reason.strip():
        raise ValueError("a test-set access needs a written reason")

    path = DEFAULT_ACCESS_LOG if log_path is None else log_path
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(_ACCESS_LOG_HEADER)

    stamp = dt.datetime.now(dt.UTC).isoformat(timespec="seconds")
    sha = _git_commit() if commit is None else commit
    with path.open("a") as handle:
        handle.write(f"{stamp} | {sha} | {reason.strip()}\n")


def _git_commit() -> str:
    """Short commit hash, or ``unknown`` outside a repository."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return "unknown"
    return result.stdout.strip() if result.returncode == 0 else "unknown"
