"""How data is split into train, validation and test (spec 3.3, ADR 0003, ADR 0037).

GUARDED AREA -- this is the data split.

**GuitarSet's players 01-05 are test-only.** No tuning, no hyperparameter search, no
threshold sweep, no model selection and no architecture choice may consult a number
measured on them. **Player 00 is validation data** (ADR 0037, amending ADR 0003): it is
there to choose with, so that choices are made on playing like the test set's.

This module exists to make that mechanical rather than remembered:

- :func:`guitarset_track_ids` reads a committed snapshot, never a glob over whatever
  happens to be on disk, so the corpus cannot drift with a partial download, and
  :func:`split_by_player` derives the two lists from it.
- :func:`assert_tuning_allowed` raises for :attr:`Split.TEST`. Every tuning entry point
  calls it first.
- :func:`assert_no_test_tracks` raises for a set of tracks holding a test track, so
  per-track counts that a decoder is chosen with cannot come from the test players.
- :func:`record_test_set_access` appends to an audit log, so looking at test numbers is
  a deliberate act with a written reason.
"""

from __future__ import annotations

import datetime as dt
import subprocess
from collections import Counter
from collections.abc import Iterable, Sequence
from enum import Enum
from pathlib import Path

from tabsampler.errors import TestSetMisuseError

#: GuitarSet contains 360 excerpts: 6 players x 5 styles x 3 chord progressions x 2 tempi
#: x 2 (comping and soloing). A snapshot with any other count means a partial or corrupted
#: download, which would silently change the corpus every metric is computed over.
EXPECTED_GUITARSET_TRACKS = 360

#: Each player records the same 30 lead sheets, comping and soloing.
TRACKS_PER_PLAYER = 60

#: The player whose recordings are validation data (ADR 0037): the lowest ID, fixed by rule
#: before any per-player figure was looked at. Players 01-05 are the test set.
VALIDATION_PLAYER = "00"

#: The committed snapshot of every GuitarSet track id, generated by
#: scripts/download_guitarset.py and reviewed in its diff. It defines the corpus for the
#: life of the project; ADR 0037 splits it by player.
DEFAULT_SNAPSHOT = Path(__file__).parent / "guitarset_test_ids.txt"

DEFAULT_ACCESS_LOG = Path("experiments/test_set_access.log")

_ACCESS_LOG_HEADER = (
    "# Every deliberate look at the test set, per ADR 0003.\n"
    "# Appended automatically by tabsampler.data.splits.record_test_set_access.\n"
    "# Columns: iso8601_utc | commit | reason\n"
)


class Split(Enum):
    """The only three splits this project recognises."""

    TRAIN = "train"
    VALIDATION = "validation"
    TEST = "test"


def guitarset_track_ids(
    snapshot: Path | None = None,
    expected_count: int | None = EXPECTED_GUITARSET_TRACKS,
) -> tuple[str, ...]:
    """Every GuitarSet track id, read from the committed snapshot.

    Args:
        snapshot: Path to the snapshot file. Defaults to the packaged one.
        expected_count: Reject the snapshot unless it holds exactly this many ids.
            Pass ``None`` to skip the check (used only by tests with small fixtures).

    Raises:
        FileNotFoundError: if the snapshot has not been generated yet.
        ValueError: if the snapshot is empty, unsorted, contains duplicates, or has an
            unexpected number of entries.
    """
    path = DEFAULT_SNAPSHOT if snapshot is None else snapshot
    if not path.is_file():
        raise FileNotFoundError(
            f"no GuitarSet split snapshot at {path}. Generate it with "
            f"`uv run python scripts/download_guitarset.py`, then review the diff -- "
            f"this file defines the test set for the life of the project."
        )

    ids = [
        line.strip()
        for line in path.read_text().splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]

    if not ids:
        raise ValueError(
            f"the split snapshot at {path} is empty; an empty test set would evaluate "
            f"nothing and report a vacuous score"
        )
    if len(set(ids)) != len(ids):
        duplicates = sorted({i for i in ids if ids.count(i) > 1})
        raise ValueError(f"duplicate track ids in {path}: {duplicates}")
    if ids != sorted(ids):
        raise ValueError(
            f"track ids in {path} are not sorted; a stable order keeps the split "
            f"reproducible and its diffs readable"
        )
    if expected_count is not None and len(ids) != expected_count:
        raise ValueError(
            f"{path} holds {len(ids)} track ids but expected {expected_count}; "
            f"a truncated snapshot silently changes the evaluation corpus"
        )

    return tuple(ids)


def split_by_player(ids: Sequence[str], player: str) -> tuple[tuple[str, ...], tuple[str, ...]]:
    """(the player's track ids, everyone else's), in snapshot order.

    A track id starts with its player's two-digit ID (``00_BN1-129-Eb_comp``).

    Raises:
        ValueError: if any player has other than :data:`TRACKS_PER_PLAYER` tracks -- a
            partial download would otherwise split unevenly and silently shrink one side --
            or if ``player`` has no tracks at all.
    """
    counts = Counter(track.split("_", 1)[0] for track in ids)
    wrong = {who: n for who, n in sorted(counts.items()) if n != TRACKS_PER_PLAYER}
    if wrong:
        raise ValueError(
            f"every GuitarSet player has {TRACKS_PER_PLAYER} tracks; these do not: {wrong}"
        )
    if player not in counts:
        raise ValueError(f"no GuitarSet tracks for player {player!r}")
    held = tuple(t for t in ids if t.split("_", 1)[0] == player)
    rest = tuple(t for t in ids if t.split("_", 1)[0] != player)
    return held, rest


def guitarset_validation_ids(snapshot: Path | None = None) -> tuple[str, ...]:
    """Player 00's 60 tracks: validation data (ADR 0037)."""
    return split_by_player(guitarset_track_ids(snapshot), VALIDATION_PLAYER)[0]


def guitarset_test_ids(snapshot: Path | None = None) -> tuple[str, ...]:
    """Players 01-05's 300 tracks: the test set, test-only (ADR 0003, ADR 0037)."""
    return split_by_player(guitarset_track_ids(snapshot), VALIDATION_PLAYER)[1]


def assert_tuning_allowed(split: Split) -> None:
    """Refuse to tune, select or sweep against the test split.

    Call this at the top of every entry point that fits a parameter to data.

    Raises:
        TestSetMisuseError: if ``split`` is :attr:`Split.TEST`.
    """
    if split is Split.TEST:
        raise TestSetMisuseError(
            "refusing to tune against the test split: GuitarSet's players 01-05 are "
            "test-only (ADR 0003, ADR 0037). Tune on a validation split: GuitarSet's "
            "player 00, or DadaGP's validation side."
        )


def assert_no_test_tracks(track_ids: Iterable[str], snapshot: Path | None = None) -> None:
    """Refuse a set of tracks that holds any of GuitarSet's test tracks.

    For whatever chooses with per-track counts, such as ``scripts/compare_validation.py``:
    a test-player track among them would make the choice on the test set. Ids that are not
    GuitarSet tracks at all, such as DadaGP songs, pass.

    Raises:
        TestSetMisuseError: naming the test tracks found.
    """
    found = sorted(set(track_ids) & set(guitarset_test_ids(snapshot)))
    if found:
        shown = ", ".join(found[:3]) + (" ..." if len(found) > 3 else "")
        raise TestSetMisuseError(
            f"{len(found)} GuitarSet test tracks (players 01-05), which nothing may be chosen "
            f"with (ADR 0003, ADR 0037): {shown}"
        )


def record_test_set_access(
    reason: str,
    log_path: Path | None = None,
    commit: str | None = None,
) -> None:
    """Append a line to the test-set access log.

    Args:
        reason: Why the test set is being looked at. Required; an entry without a
            reason defeats the purpose of the log.
        log_path: Where to append. Defaults to ``experiments/test_set_access.log``.
        commit: Git commit to attribute the look to. Resolved automatically if omitted.

    Raises:
        ValueError: if ``reason`` is blank.
    """
    if not reason.strip():
        raise ValueError("a test-set access needs a written reason")

    path = DEFAULT_ACCESS_LOG if log_path is None else log_path
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(_ACCESS_LOG_HEADER)

    stamp = dt.datetime.now(dt.UTC).isoformat(timespec="seconds")
    sha = _git_commit() if commit is None else commit
    with path.open("a") as handle:
        handle.write(f"{stamp} | {sha} | {reason.strip()}\n")


def _git_commit() -> str:
    """Short commit hash, or ``unknown`` outside a repository."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return "unknown"
    return result.stdout.strip() if result.returncode == 0 else "unknown"
