"""Download EGDB's labels and direct-input audio, and write its test-set snapshot (ADR 0050).

    uv run python scripts/download_egdb.py

EGDB is shared as a Google Drive folder, linked from https://ss12f32v.github.io/Guitar-Transcription/.
This lists it with ``gdown`` (run through ``uvx``, not a project dependency), fetches
``audio_label/`` and ``audio_DI/`` into ``data/egdb/`` -- the amplifier renderings are not
fetched, the target being clean electric (ADR 0049) -- skips what is already there, checks that
all 240 clips have both, and writes ``src/tabsampler/data/egdb_test_ids.txt``. Review that diff:
the file defines a test set. Everything EGDB holds is test data; nothing here reads a label.
"""

from __future__ import annotations

import json
import subprocess
import time
from pathlib import Path

from tabsampler.data.splits import EGDB_SNAPSHOT, EXPECTED_EGDB_CLIPS, egdb_clip_id

FOLDER = "https://drive.google.com/drive/folders/1h9DrB4dk4QstgjNaHh7lL7IMeKdYw82_"
ROOT = Path("data/egdb")
WANTED = ("audio_label", "audio_DI")


def listing() -> list[dict[str, str]]:
    """Every file in the folder: ``{"url": ..., "path": ...}``."""
    out = subprocess.run(
        ["uvx", "gdown", "--json", FOLDER], capture_output=True, text=True, check=True
    ).stdout
    entries: list[dict[str, str]] = json.loads(out)
    return entries


def fetch(url: str, target: Path, tries: int = 3) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    for attempt in range(tries):
        result = subprocess.run(["uvx", "gdown", "-q", url, "-O", str(target)], check=False)
        if result.returncode == 0 and target.stat().st_size > 0:
            return
        time.sleep(10 * (attempt + 1))
    raise RuntimeError(f"could not fetch {target} from {url}")


def main() -> None:
    wanted = [e for e in listing() if e["path"].split("/")[0] in WANTED]
    for entry in wanted:
        target = ROOT / entry["path"]
        if not (target.exists() and target.stat().st_size > 0):
            fetch(entry["url"], target)
    numbers = sorted(int(p.stem) for p in (ROOT / "audio_label").glob("*.midi"))
    missing = [n for n in numbers if not (ROOT / "audio_DI" / f"{n}.wav").exists()]
    if len(numbers) != EXPECTED_EGDB_CLIPS or missing:
        raise SystemExit(f"{len(numbers)} label files, DI missing for {missing}: incomplete")
    EGDB_SNAPSHOT.write_text(
        "# Every EGDB clip id (ADR 0050): the second test set, all of it test-only.\n"
        "# Clips 1-240 of the dataset's Google Drive folder, listed 2026-10-06; generated by\n"
        "# scripts/download_egdb.py. Review any diff to this file: it defines a test set.\n"
        + "".join(f"{egdb_clip_id(n)}\n" for n in numbers)
    )
    print(f"{len(numbers)} clips with labels and DI audio; snapshot written to {EGDB_SNAPSHOT}")


if __name__ == "__main__":
    main()
