"""Download GuitarSet and generate the test-split snapshot.

GuitarSet is test-only (ADR 0003). This script does two things:

1. Downloads only ``annotations`` and ``audio_mic``. The hex-pickup archives are
   several GB and are forbidden as transcriber input anyway, because one channel per
   string is the E2 ground truth (ADR 0005).
2. Writes ``src/tabsampler/data/guitarset_test_ids.txt``, the committed snapshot that
   defines the test set for the life of the project. **Review its diff.**

Usage:
    uv run python scripts/download_guitarset.py
    uv run python scripts/download_guitarset.py --snapshot-only   # no download
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from tabsampler.data.guitarset import REQUIRED_REMOTES, load_dataset  # noqa: E402
from tabsampler.data.splits import DEFAULT_SNAPSHOT, EXPECTED_GUITARSET_TRACKS  # noqa: E402

SNAPSHOT_HEADER = (
    "# GuitarSet track ids. Generated by scripts/download_guitarset.py.\n"
    "# Player 00's 60 tracks are validation data; players 01-05's 300 are the test set,\n"
    "# test-only (ADR 0003, ADR 0037). This file defines the corpus for the life of the\n"
    "# project -- review every change to it in the diff.\n"
    f"# Expected: {EXPECTED_GUITARSET_TRACKS} tracks, sorted, unique.\n"
)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--data-home",
        type=Path,
        default=Path("data/guitarset"),
        help="Where GuitarSet lives (default: data/guitarset).",
    )
    parser.add_argument(
        "--snapshot-only",
        action="store_true",
        help="Skip the download; just regenerate the split snapshot.",
    )
    parser.add_argument(
        "--skip-validate",
        action="store_true",
        help="Skip mirdata's checksum validation (it is slow).",
    )
    args = parser.parse_args()

    data_home: Path = args.data_home
    data_home.mkdir(parents=True, exist_ok=True)
    dataset: Any = load_dataset(data_home)

    if not args.snapshot_only:
        print(f"Downloading GuitarSet remotes {list(REQUIRED_REMOTES)} into {data_home} ...")
        print("(skipping the hex-pickup archives: several GB, and forbidden as input)")
        dataset.download(partial_download=list(REQUIRED_REMOTES))

    if not args.skip_validate:
        print("Validating ...")
        missing, invalid = dataset.validate()
        for label, report in (("missing", missing), ("invalid checksum", invalid)):
            for kind, items in report.items():
                # Other channels are legitimately absent after a partial download.
                if kind in REQUIRED_REMOTES or kind == "tracks":
                    relevant = {
                        k: v
                        for k, v in items.items()
                        if not any(skip in str(v) for skip in ("hex", "mix"))
                    }
                    if relevant:
                        print(f"  WARNING {label} in {kind}: {len(relevant)} entries")

    track_ids = sorted(dataset.track_ids)
    print(f"\n{len(track_ids)} tracks found.")
    if len(track_ids) != EXPECTED_GUITARSET_TRACKS:
        print(
            f"ERROR: expected {EXPECTED_GUITARSET_TRACKS} tracks, found {len(track_ids)}. "
            f"Refusing to write a snapshot: a truncated split would silently change "
            f"the corpus every metric is computed over.",
            file=sys.stderr,
        )
        return 1

    DEFAULT_SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
    DEFAULT_SNAPSHOT.write_text(SNAPSHOT_HEADER + "\n".join(track_ids) + "\n")
    print(f"Wrote {DEFAULT_SNAPSHOT} ({len(track_ids)} ids).")
    print("\nNow review that file's diff before committing. It defines the test set.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
